name: DeployFunctionApp

on:
  workflow_dispatch:
    inputs:
      folder_name:
        description: 'the function to deploy'
        required: true
        type: string
      machine_name:
        description: 'the machine to deploy the function to'
        required: true
        type: string
      environment:
        description: 'environment to deploy (e.g. production, development)'
        default: 'production'
        required: false
        type: string
      python_version:
        description: 'Version of python to use'
        default: '3.11'
        required: false
        type: string 
env:
  package_path: './functionapps/${{inputs.folder_name}}/'
  target_package_path: './${{inputs.machine_name}}/'
  GIT_MACHINE_TOKEN: ${{secrets.GIT_MACHINE_TOKEN}}
  GIT_MACHINE_USER: ${{secrets.GIT_MACHINE_USER}}
    
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    steps:
    - name:
      id: vars
      run: |
        fname=${{inputs.machine_name}}
        ufname=${fname^^}
        echo "SECRET_NAME=${ufname//-/_}_PUBLISH_PROFILE" >> $GITHUB_OUTPUT

    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
    
    - name: Setup Python ${{inputs.python_version}} Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{inputs.python_version}}
    
    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Resolve project dependencies using pip
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r ${{env.package_path}}requirements.txt --target=".python_packages/lib/site-packages"

    - name: Run Azure Functions Action
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{inputs.machine_name}}
        package: ${{env.package_path}}
        publish-profile: ${{secrets[steps.vars.outputs.SECRET_NAME]}}
        enable-oryx-build: true 
        scm-do-build-during-deployment: true